name: Update EFS

on:
  workflow_dispatch:
    inputs:
      eks_cluster:
        description: "Please enter Cluster Name"
        required: true
      namespace:
        description: "Please enter 'Namespace Name"
        required: false
      efs_id:
        description: "Please enter EFS Id"
        required: true
      IsRecoveyMode:
        description: 'Please cehck if it is Recovery Mode'
        required: true  
        type: bool   
jobs:
    configure-task:
       runs-on: ubuntu
       steps:
        - name: test
          run: echo "hello"
